mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.boot.demo.pojo
#数据库连接池
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/mysql-test?serverTimezone=CST
    driver-class-name: com.mysql.jdbc.Driver
#让控制台打印自动配置报告
#debug: true